name: C Code Tests

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or SHA to test (optional)"
        required: false
  push:
    branches: [ main, master, develop, '*' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show toolchain versions
        run: |
          uname -a || true
          gcc --version || true
          clang --version || true
          timeout --version || true

      - name: Run C tests
        shell: bash
        run: |
          chmod +x scripts/run_c_tests.sh
          scripts/run_c_tests.sh

      - name: Upload build outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: c-test-outputs
          path: scripts/c-tests/build
          if-no-files-found: warn
